"""Built-in Govee scene metadata."""

from __future__ import annotations

BUILTIN_SCENES = {'H6022': [{'category': 'Custom',
            'code': 8505,
            'name': 'Fast Fire',
            'param': 'AA8OYBj/ZAD/ZAD/ZAD/ZAD/ZAD/ZAD/ZAD/ZAA='},
           {'category': 'Custom',
            'code': 8505,
            'name': 'Flash (Sound)',
            'param': 'AAQIQBgAlhTd3wDj5Rb/qwD3eXbYg/+TNv06hv8='},
           {'category': 'Custom',
            'code': 8505,
            'name': 'Spin (Sound)',
            'param': 'AAQHQBgAlhTd3wDj5Rb/qwD3eXbYg/+TNv06hv8='},
           {'category': 'Custom',
            'code': 8505,
            'name': 'Lightning (Sound)',
            'param': 'AAQGQBgAlhTd3wDj5Rb/qwD3eXbYg/+TNv06hv8='},
          {'category': 'Natural',
            'code': 8478,
            'name': 'Sunrise',
            'param': 'QQEBAWQAAasAA50ABhI6hv8AAQIDBAUGBwgJCgsMDhASFBYY+K2dDQ8RExUXGBkaGxwdHh8gISIjJCYoKiwuMP++CyUnKSstLzAxMjM0NTY3ODk6Ozw9Pj9AQUJDREVGR0hJSktMTU5PUFFSU1RWWFpcXgb/fwBVV1lbXV8S+1YHYGFiY2RlZmdoaWprbG5wcnR2Ev8AAG1vcXN1d3h5ent8fX5/gIGCg0tkAwAB//8AAAAA'},
           {'category': 'Natural',
            'code': 8479,
            'name': 'Sunset',
            'param': 'QQEBAWQAAa8AA6EABxj/AAAAAQIDBAUGBwgJCgsMDQ4PEBESExQVFhcS9wAAGBkaGxwdHh8gISIjJCYoKiwuHvtWByUnKSstLzAxMjM0NTY3ODk6Ozw9Pj9AQUJDREVGRwz/fwBISUpLTE1OT1BRUlMY/5UFVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprDP++C2xtbm9wcXJzdHV2dwz/4BZ4eXp7fH1+f4CBgoMyZAMAAf//AAAAAA=='},
           {'category': 'Natural', 'code': 42, 'name': 'Rainbow', 'param': ''},
           {'category': 'Natural',
            'code': 8480,
            'name': 'Sunset Glow',
            'param': 'QQEBAWQAA68AA6EABxj7VgcAAQIDBAUGBwgJCgsMDQ4PEBESExQVFhcP/38AGBkaYmNkZWZsbW50dXZ3EP+3ABscHR4fICEiIyQlJicoMDEn/588KSorLC0yMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTAv+VBS4vE/+GAFRVVldYWVpbXF1eX2BhZ2hpamsR/wAAb3BxcnN4eXp7fH1+f4CBgoMyZAQAAv//AAAAADsAAy0AAhj7VgdISUpLTE1OT1BRUlNUVVZXWFlaW1xdXl8M/wAAYGFiY2RlZmdoaWprRmQBAAH//wAAAABHAAM5AAIY//8ADA0ODxAREhMUFRYXGBkaGxwdHh8gISIjGP9/ACQlJicoKSorLC0uLzAxMjM0NTY3ODk6O0ZkAgAB//8AAAAA'},
           {'category': 'Natural',
            'code': 8481,
            'name': 'Aurora',
            'param': 'QQD/AGQAAi0AAx8AARoAAP8LFRYgISorLDQ1Nj4/QElKS1VdYGdocnN8fVFkBgAB//8AAAAAIgADFAABD4sA/xchIiwtNjc4Qmhpc3R+f1lkBgAB//8AAAAA'},
           {'category': 'Natural', 'code': 44, 'name': 'Forest', 'param': ''},
           {'category': 'Natural', 'code': 43, 'name': 'Ocean', 'param': ''},
           {'category': 'Natural', 'code': 46, 'name': 'Wave', 'param': ''},
           {'category': 'Natural', 'code': 41, 'name': 'Snow flake', 'param': ''},
           {'category': 'Natural',
            'code': 8482,
            'name': 'Spring Wind',
            'param': 'QQEBAWQAAqcAA5kABVsA/wAAAQIDBAYHCgsMDQ4PEhQVFhcYGRodHh8gISIjJCgpKissLzEyMzQ1Njc6Ozw9Pj9AREVGR0hJSktPUFFUVVpbXF9gZGVmZ2tub3BxcnV2d3h5ent8fX+AgYKDC///AAUQERwnUl1oaXN+E/8AAAgJExslJi0uMDg5QkNNTlhiY20GMf+TQUxWV2FsBf9/AFNZXmp0V10GAAL//wAAAAAqAAMcAAIKAP//CRQfKjVAS1ZhbAly/3IjLjlERU9QW2ZcZAYAAf//AAAAAA=='},
           {'category': 'Natural',
            'code': 8483,
            'name': 'Sky',
            'param': 'QQZy/0EAA2kAA1sAAxgAAP8AAQIDBAUGBwgJCgsMDQ4PEBESExQVFhckAIj/SUtNT1FTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG5wcnR2Ev///21vcXN1d3h5ent8fX5/gIGCgx5kAwAC//8AAAAAHgADEAABC////01OT1BWV1hZc3R1VWQEAAH//wAAAAAkAAMWAAER////QkNETE1OT1BcXV5gYWJub3BVZAMAAf//AAAAAA=='},
           {'category': 'Natural',
            'code': 8484,
            'name': 'Firefly',
            'param': 'QQBbJDIAAxgAAwoAAQXj5RYOF05VdTxQAAAC//8AAAAAFwADCQABBL/SAA4iYWg3MgcAAf//AAAAABYAAwgAAQP/0gAfSV9LWgQAAf//AAAAAA=='},
           {'category': 'Natural', 'code': 40, 'name': 'Fire', 'param': ''},
           {'category': 'Natural',
            'code': 8485,
            'name': 'Falling Petals',
            'param': 'QQe+uDwAAzcAAykABAj/AKYHEhMUHh8gKwb/AAAlMDE8PUkC/0QHMj4IiwD/UVxdXmhpanVSZAIAAf//AAAAACcAAxkAAgj/fwAKFRYXISIjLgj//wBMV1hZY2RlcF9kAgAC//8AAAAAJQADFwADBv9/AA4yRFlhdwL/AAAqUAL//wA+a1ZkCAAD//8AAAAA'},
           {'category': 'Natural',
            'code': 8486,
            'name': 'Cherry blossoms',
            'param': 'QQEBAWQAAyYAAxgAARP/AG4ABRUaGyEiJzZCQ0leY2Rqa3B/VWQIAAH//wAAAACfAAORAAMU/wBuAAECAwQFBgcICQoLDA4QEhMUFx9k//CQDQ8RFRYYGRobHB0eICEiIyQlJicoKSorLC0uLzAxMjM0NTY3ODk6Ozw9Pj9AQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVpbXF1eX2BhYmNkZWZnaGlqa2xtbm9wcXJzdHV2dwzphYd4eXp7fH1+f4CBgoMyRgMAA///AAAAABYAAwgAAQP/Q1IUXGFVZAcAAv//AAAAAA=='},
           {'category': 'Natural',
            'code': 8487,
            'name': 'Raining',
            'param': 'QQDQjjAAAxwAAw4AAQn///8OITVBU1VhaHRkZAIAAf//AAAAACUAAxcAARL///9sb3B0dXZ4eXp7fH1+f4CBgoNGNgMAAv//AAAAACUAAxcAARL///9sb3B0dXZ4eXp7fH1+f4CBgoNGNgQAAv//AAAAAA=='},
           {'category': 'Natural',
            'code': 8488,
            'name': 'Desert',
            'param': 'QcxYAwwAAjwAAy4AASn//wAJChUWQk1OT1hZWltcY2RlZmdoaW5vcHFyc3R1dnh5ent8fX5/gIGCgxFkBAAC//8AAAAAHQADDwABCv//AAIOFjQ/WmFpbHVPZAYAAf//AAAAAA=='},
           {'category': 'Natural',
            'code': 8489,
            'name': 'Karst Cave',
            'param': 'QQEBAWQAAjUAAycAAhKLAP8AAQIDBAUGBwgJCgsNDxETFRcMAAD/eHl6e3x9fn+AgYKDMhYDAAH//wAAAACBAANzAAkF//8AGSUxVWEF/38AGiYyVmIF+1YHGyczV2MK/wAAHB0oKTQ1WFlkZQX/AG4eKjZaZgeDOOwgLDc4W1xoCgD/ACEiLS45Ol1eaWoHAP//Iy8wO1RfaxgAAP88PT4/QEFCQ0RFRkdISUpLTE1OT1BRUlNQZAMAAf//AAAAAA=='},
           {'category': 'Natural',
            'code': 8490,
            'name': 'Mountain Forest',
            'param': 'QQCs5yUAA0wAAz4AAy4A/wAzP0pLTFJVVlhZXV5fYGFiY2RlZmhqa2xub3BxcnN0dXZ3eHl6e3x9fn+AgYKDAv/wbFdtAf+fPGkwZAMAAf//AAAAAF4AA1AAAiAk8pweKSorNDU2Nzg/QEFCQ0RLTE1OT1BYWVpbXGVmZ3FycycA0I4kMDE7PD1GR0hJSlFSU1RVVlddXl9gYWJjZGhpamtsbW5vcHR1dndOUAMAAv//AAAAABcAAwkAAQT8/6YODyEiRGQDAAH//wAAAAA='},
           {'category': 'Natural',
            'code': 8491,
            'name': 'Feather',
            'param': 'QQEBAWQAAyIAAxQAAQ////8GDBkhJi41O0JPVGF2fYNOZAIAAf//AAAAABoAAwwAAQf///8JDRYaT1xpUFACAAL//wAAAACbAAONAAJ4AKAAAAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3DP///3h5ent8fX5/gIGCgzIyAwAD//8AAAAA'},
           {'category': 'Natural',
            'code': 8492,
            'name': 'Spring',
            'param': 'QQEBAUYAA30AA28ABQv/ANYlJiorLC8wNDU5Ohj/fwAxMjY3PD0+P0BBQkNERUZHSElNTlFSWl4M/wAAMzg7SktMT1BTVVldC///AFRWWFxfYGFiZmlqIAD/AFdbY2RlZ2hrbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDPGQEAAH//wAAAABTAANFAAIY//8AAAECAwQFBgcICQoLDA0ODxAREhMUFRYXJP//ZhgZGhscHR4fICEiIyQlJicoKSorLC0uLzAxMjM0NTY3ODk6O0ZkAwAD//8AAAAAKwADHQABGP//AAABAgMEBQYHCAkKCwwNDg8QERITFBUWF1BkAgAB//8AAAAA'},
           {'category': 'Natural',
            'code': 8493,
            'name': 'Summer',
            'param': 'QQEBAWQAAn8AA3EABB4x/5MAAQIDBAUGBwgJCgsMDQ4PEBESExQVFhcZGx0fISMY//BsGBocHiAiJCUmJygpKissLS4vSElKS0xNHv/wkDAxMjM0NTY3ODk6Ozw9Pj9AQUJDREVGR05PUFFSUwz/zEFUVVZXWFlaW1xdXl8yZAQAAf//AAAAAGYAA1gAAyH/fwAuMDQ5Ojs8PT9AQURFRkdISUpLTE1OT1BRUlNUVlhaXF4a/18oVVdZW11fYGFiY2RlZmdoaWprbG1ub3BxcnMQ+1YHdHV2d3h5ent8fX5/gIGCg1FYAwAB//8AAAAA'},
           {'category': 'Natural',
            'code': 8494,
            'name': 'Fall',
            'param': 'QQEBAS8AAxYAAwgAAQP/fwAcaGxWZAIAAv//AAAAACUAAxcAARL/fwAAAQIDBAUGBwgJCgsNDxETFRcyZAMAAf//AAAAABgAAwoAAQX/hgAKJkVlgkJEBwAB//8AAAAA'},
           {'category': 'Natural',
            'code': 8495,
            'name': 'Winter',
            'param': 'QQEBAWQAAxsAAw0AAQj///8LEiY6TlRwdVpkAgAB//8AAAAAGAADCgABBf///xQZQWJ1S2QCAAH//wAAAACrAAOdAAYMGgD/AAECAwQFBgcICQoLNgAA/wwNDg8QERITFBUWFxgZGhscHR4fICEiIyQlJicoKSorLC0uLzAxMjM0NTY3ODk6Oz0/QUNFRyoGcv88PkBCREZISUpLTE1OT1BRUlNUVVZXWFlaW1xdXl9gYWJjZGVmZ2hpamsE2+TubHBxcwY6hv9tbnJ1dncO////b3R4eXp7fH1+f4CBgoNGRgMAAv//AAAAAA=='},
           {'category': 'Natural',
            'code': 8496,
            'name': 'Lake',
            'param': 'QQEBAUIAAz8AAzEAASwAAP9ET1BRVVpbXF1eYGFiZWZnaGlqa2xtbm9wcXJzdHV2d3h5ent8fX5/gIGCg0tfBAAC//8AAAAAFwADCQABBP//AA8QGxxLZAMAAf//AAAAAGsAA10AAhgA0I4AAQIDBAUGBwgJCgsMDQ4PEBESExQVFhc8JdtdGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTMmQDAAP//wAAAAA='},
           {'category': 'Life', 'code': 99, 'name': 'White Light', 'param': ''},
           {'category': 'Life', 'code': 35, 'name': 'Reading', 'param': ''},
           {'category': 'Life', 'code': 38, 'name': 'Night Light', 'param': ''},
           {'category': 'Life',
            'code': 8497,
            'name': 'Morning',
            'param': 'QQEBAWQAApsAA40AAhj/xjQAAQIDBAUGBwgJCgsMDhASFBYZGx0fISNsMf+TDQ8RExUXGBocHiAiJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDTmQDAAL//wAAAAA7AAMtAAIGAP//VFZYWlxeHgCI/2FjZWdpa2xtbm9wcXJzdHV2d3h5ent8fX5/gIGCg0ZkBAAB//8AAAAA'},
           {'category': 'Life',
            'code': 8498,
            'name': 'Afternoon',
            'param': 'QQEBAWQAAp8AA5EAAxL/4m8AAQIDBAUGBwgJCgsNDxETFRcq/8xBDA4QEhQWGBkaGxwdHh8gISIjJCUmJygpKissLS4vMTM1Nzk7PD5AQkRGSP/wbDAyNDY4Oj0/QUNFR0hJSktMTU5PUFFSU1RVVldYWVpbXF1eX2BhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ent8fX5/gIGCgzJkBAAC//8AAAAAYgADVAACJ//GNC4wNDk6Ozw9P0BBREVGR0hJSktMTU5PUFFSU1VXWVtdX2BiZGZoaiT/twBUVlhaXF5hY2VnaWtsbW5vcHFyc3R1dnd4eXp7fH1+f4CBgoNAZAMAAf//AAAAAA=='},
           {'category': 'Life',
            'code': 8499,
            'name': 'Leisure',
            'param': 'QQEBAWQAAp8AA5EAAyT/fwAAAQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyAhIiM2/7cAJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFZYWlxeKv/MQVVXWVtdX2BhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ent8fX5/gIGCg0ZaBAAC//8AAAAAWQADSwACGP/MQTw+QEJERkhJSktMTU5PUFFSU1RWWFpcXir/twBVV1lbXV9gYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXp7fH1+f4CBgoNAZAMAAf//AAAAAA=='},
           {'category': 'Life',
            'code': 8500,
            'name': 'Refreshing',
            'param': 'Qf///2QAAmMAA1UAAyRy/3IxMzU3OTs8PkBCREZISUpLTE1OT1BRUlNgYWJjZGVmZ2hpamsMMf+TVFVWV1hZWltcXV5fGAD/AGxtbm9wcXJzdHV2d3h5ent8fX5/gIGCg1NkBAAB//8AAAAAHwADEQABDAD//wABAgMEBQYHCAkKC1NRAwAB//8AAAAA'},
           {'category': 'Life',
            'code': 8501,
            'name': 'Fish tank',
            'param': 'QQD/AAQAAjcAAykAASQA/wAAAQIDBAUGBwgJCgtsbW5vcHFyc3R1dnd4eXp7fH1+f4CBgoMAFAAAAv//AAAAADcAAykABgOLAP8YGS4DAP//H1JTAv9/ACcoBP//AC09WFkC/wAAPmkCAAD/QkNGZAQAAf//AAAAAA=='},
           {'category': 'Life',
            'code': 8502,
            'name': 'Goldfish',
            'param': 'QQAA/0YAAiwAAx4AARkDqzZiY2hpamxtbm9yc3R1eHl6e3x9fn+AgYKDPGQDAAL//wAAAAArAAMdAAIQ/74LHikqNDU2P0BBQkxNTllaZgT7Vgc4Q0RQRmQDAAH//wAAAAA='},
           {'category': 'Life',
            'code': 8503,
            'name': 'Train',
            'param': 'QQBe/0EAAkQAAzYABAv/AABVVldhYmNub3l6ewwA/wBYWVpkZWZwcXJ8fX4M/38AW1xdZ2hpc3R1f4CBAv//AGxtWWQDAAH//wAAAAAfAAMRAAEM////AwsXHCEsNkBCVmJtTGQBAAL//wAAAAA='},
           {'category': 'Life',
            'code': 8504,
            'name': 'Kitchen Aromas',
            'param': 'QQA8/zQAAjEAAyMAAR4A/wRWX2FiY2Rqa2xtbm9wcXR1dnd4eXp7fH1+f4CBgoNMZAMAAf//AAAAACwAAx4AARn///8ABwsMEhkdIyUpLjY8Q0dIT1VaYWVtcnh+VmQBAAL//wAAAAA='},
           {'category': 'Life',
            'code': 8505,
            'name': 'Breathe',
            'param': 'AAUAIxgAlhTd3wDj5Rb/qwD3eXbYg/+TNv06hv8='},
           {'category': 'Life',
            'code': 8506,
            'name': 'Gradient',
            'param': 'AAAACBhaAIRsAKVLGbcAjAAAlUwGcv8iI/YANKA='},
           {'category': 'Natural',
            'code': 8505,
            'name': 'Fire',
            'param': 'AA8AIwz/AAD/UAD/tAD//wA='},
           {'category': 'Natural',
            'code': 8505,
            'name': 'Rainbow',
            'param': 'AAkAIxX/AAD/fwD//wAA/wAAAP8A//+LAP8='},
           {'category': 'Life',
            'code': 8508,
            'name': 'Dream 1',
            'param': 'AA4NIxX/AAD/fwD//wAA/wAAAP8A//+LAP8='},
           {'category': 'Life',
            'code': 8508,
            'name': 'Dream 2',
            'param': 'AA4OVQ9S4+H/qwD3eXbYg/+TNv0='},
           {'category': 'Life',
            'code': 8507,
            'name': 'Graffiti 1',
            'param': 'AFINIxX/AAD/fwD//wAA/wAAAP8A//+LAP8='},
           {'category': 'Life',
            'code': 8507,
            'name': 'Graffiti 2',
            'param': 'AFIOIxX/AAD/fwD//wAA/wAAAP8A//+LAP8='},
           {'category': 'Life',
            'code': 8507,
            'name': 'Graffiti 3',
            'param': 'AFI5SBj/vgv7Vgf/AACDOOwAOrcA/wAAAP8A//8='},
           {'category': 'Life', 'code': 45, 'name': 'Joyful', 'param': ''},
           {'category': 'Life',
            'code': 8509,
            'name': 'Smudge',
            'param': 'QQEBAWQAAZsAA40ABRj/AAAAAQIDBAUGBwgJCgsMDQ4PEBESExQVFhcY//8AGBkaGxwdHh8gISIjJCUmJygpKissLS4vGAD/ADAxMjM0NTY3ODk6Ozw9Pj9AQUJDREVGRxgAAP9ISUpLTE1OT1BRUlNUVVZXWFlaW1xdXl8YiwD/YGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3VWQCAAH//wAAAAA='},
           {'category': 'Life',
            'code': 8510,
            'name': "Rubik's Cube",
            'param': 'QQEBAWQAAaMAA5UABDn/AAAAAQIMDQ4YGRonKCktLi8zNDU5Ojs/QEFFRkdLTE1RUlNUVVZaW1xgYWJmZ2hsbW5yc3R4eXp+f4AS//8AAwQFCQoLDxARFRYXGxwdISIjIQAA/wYHCBITFB4fICQlJjAxMjw9PkhJSl1eX2lqa3V2d4GCgxgA/wAqKyw2NzhCQ0ROT1BXWFljZGVvcHF7fH1XZAQAAv//AAAAAA=='},
           {'category': 'Life',
            'code': 8511,
            'name': 'Interlaced',
            'param': 'QQAA/w0AAjEAAyMAAR7/AAAeHyQqKy8wNTY3ODs8PUBBREVGR0lKS0xRUlZXXV5QZAQAAv//AAAAAC8AAyEAARwA/wAbJicyMzQ5PT5AQURFRkhJTU5PUFJTVFpbX2ZnUGQEAAH//wAAAAA='},
           {'category': 'Life',
            'code': 8512,
            'name': 'Swing',
            'param': 'QQEBAWQBAi4AAyAAARsAAP8kMDE8PT5ISUpLVVZXWGJjZGVmcHFyc3R/gIFQZAAAAfQBAAAAAC4AAyAAARsAAP8vOjtFRkdQUVJTW1xdXmVmZ2hpb3BxcnN6e3xQZAAAAfQBAAAAAA=='},
           {'category': 'Festival',
            'code': 8513,
            'name': 'Christmas',
            'param': 'Qf8AAC0AA3oAA2wABBv//wAFBgcQERMUGxwhJictLjEyO0lKUlNUVV9td3guAP8AEh0eHyAoKSorLDM0NTY3ODk6S0xQUVZXWFlaW1xdXm5vdXZ5ent8fX5/gIGCgwr/hwBAQUJDRGRlZmdoCACpAE1OT3BxcnN0UGQEAAL//wAAAAAYAAMKAAEF/74LDiI1PV5WZAAAAf//AAAAABgAAwoAAQX/fwAbIk9Vd1BkBgAB//8AAAAA'},
           {'category': 'Festival',
            'code': 8514,
            'name': 'Halloween',
            'param': 'QQEBATMBAi8AAyEAARz7VgcaGyAhJicsLUlSVldYW1xdY2RlZmdocHFyc31+VkEAAAFYAgAAAACLAAN9AAsGBQUFAAIEBggKJykAKQEDBQcJCwwNDg8QERITFBUWFxgaHB4gIiMkJigqLC4vMDQ2ODo7Qgr7VgcyZG1vcHFyc3V3AloAhDxAAYsA/0QB/38ARw5mAABOVnh5ent8fX5/gIGCgwTMWANibnR2ASwAb2gB/wBuagH//wBsUCgDAAFwFwAAAAA='},
           {'category': 'Festival',
            'code': 8515,
            'name': 'Christmas Bell',
            'param': 'QQD/ADAAATsAAy0ABAQA//8PEBMUEP//AB0eKSo0NTY3QEFCQ0xNTk8E/38AWFtkZwT/AABZWmVmVGQDAAL//wAAAAA='},
           {'category': 'Festival',
            'code': 8516,
            'name': 'Candy Cane',
            'param': 'QQEBAWQAAZ8AA5EAA0T/AAAAAQIDBwgJDA0OEhMUGBkdHh8jJCgpKi4vMzQ1OTo7Pj9AREVGSUpLT1BRVFVWWltcX2BhZWZnamtscHFydXZ7fH2AgSkA/wAEBQoLDxAVFhobICElJissMDE2NzxBQkdMTVJXWF1iY2htbnN3eHl+ghf///8GERccIictMjg9Q0hOU1leZGlvdHp/g2RkBgAB//8AAAAA'},
           {'category': 'Festival',
            'code': 8517,
            'name': "Valentine's Day",
            'param': 'Qf+HrS0AAjMAAyUAASD/AAAMDRARGBkaGxwdJSYnKDIzWlteX2ZnaGlqa3N0dXaAgVJkAQAB//8AAAAAHgADEAABC/8AAAkUFSUxMkRPUGJ2WGQBAAL//wAAAAA='},
           {'category': 'Festival',
            'code': 8518,
            'name': 'Heartbeat',
            'param': 'QQEBASwBAx8AAxEAAQz/AAAxMjs8P0ZMUVlcZmdfZAQAArgLAAAAADUAAycAASL/AAAmJygrLC0yMzQ1Njc4OT4/QEFCQ0RFS0xNTk9QWFlaW2VmWGQAAAHoAwAAAAA1AAMnAAEi/wAAJicoKywtMjM0NTY3ODk+P0BBQkNERUtMTU5PUFhZWltlZlRkAAAB6AMAAAAA'},
           {'category': 'Festival',
            'code': 8519,
            'name': "Saint Patrick's Day",
            'param': 'Qf/Tb1oAAWwAA14AAVkA/wAAAgMEBQgJCgsNDg8QExQVFhgZGhseHyAhJCUmKSorLC8wMTQ1Njc6Ozw/QEFCRUZHSktMTVBRUlNVVldYW1xdXmBhYmNmZ2hpbG1ucXJzdHd4eXx9fn+Cg11kBgAC//8AAAAA'},
           {'category': 'Festival',
            'code': 8520,
            'name': 'Easter Egg',
            'param': 'QQEBAWQAAcMAA7UADA8A/wAAAQIDDA0ODxgZGhskJSYGgzjsBBARHB0eBYsA/wUGBxITEP//AAgJCgsUFRYXIiNub3h5ensL+1YHHyArLC0uLzg5OjsB/38AIQ8AAP8nKCkqNDU2N0BBQkNNTk8JAP//MDxIVFVgYWxtEv8AADEyMz0+P0lKS0xWV1hZYmNkZQz/vgtERUZHUFFSU1xdXl8Ma/F4WltmZ3BxcnN8fX5/DP8Abmhpamt0dXZ3gIGCg1ZkBgAB//8AAAAA'},
           {'category': 'Festival',
            'code': 8521,
            'name': 'Ghost',
            'param': 'QQEBAWQAAjEAAyMAAR4A/wAPEBscHScoKSoyMzQ1Njg5Oj9AQ0RFRk9QUVJTXl9cUAUAAv//AAAAADMAAyUAASAAAP8PEBscHScoKSoyMzQ1Njg5Oj9AQ0RFRkdPUFFSU15fajxZAAAC//8AAAAA'},
           {'category': 'Festival',
            'code': 21780,
            'name': 'Christmas Baubles',
            'param': 'Qf8AAD0AAVIAA0QAAiz//wAAAQIDBAUGBwgJCgsMDRAREhMWFx0eZWZsbXBxcnN2d3h5ent8fX5/gIGCgw////8xNTk8PT5AQUJERUZJTVFOZAMAAf//AAAAAA=='},
           {'category': 'Festival',
            'code': 21781,
            'name': 'Christmas Eve',
            'param': 'QQAA/xgAA04AA0AAAxL///8yPT4/REhJS0xPUFFUWFlbXWUa/wAASlVXXGBkZ2lsbW9wc3V4eXp7fH1+f4CBgoMH//8AVmFiY2hudARkAwAB//8AAAAAGgADDAABB////xAgPUFTWoFUZAcAAv//AAAAACkAAxsAAg8A/wACDg8aGxwdHiYnKCkqKywD/wAABBARJmQEAAP//wAAAAA='},
           {'category': 'Festival',
            'code': 21782,
            'name': 'Candy Cane B',
            'param': 'QQD/AGQAAU8AA0EAAiT/AAACAwQICQ0ODxQVFxwdIiMlKClAQUZHTE1SU2RlcHF2d3x9goMU////ChARExYZHysuLzQ1OjtYWV5famsQZAQAAf//AAAAAA=='},
           {'category': 'Festival',
            'code': 21783,
            'name': 'Santa Hat',
            'param': 'Qf//AC0AAlgAA0oAAi3/AAASExQdHh8gISgpKi0uNDU2Oj9AQUJDS0xNTk9QVldYWVpbXGJjZGVmZ2hpbnUU////JC8wO0ZHb3BxcnN0ent8fX5/gIEQZAQAAf//AAAAACMAAxUAARAA/wAAAQIDBAUGBwgJCgsMDxIWMmQEAAL//wAAAAA='},
           {'category': 'Festival',
            'code': 21784,
            'name': 'Christmas Stripe',
            'param': 'QQEBASUAAXUAA2cAAyr/AAAAAQMEBQcICw0ODxESExUWFxoeImBkaGxtb3Bxc3R1d3h5ent9fn+BgoMYAP8AGBwgJCUnKCkrLC0vMTIzNTY3OTo7PkJGGP//ADxAREhJS0xNT1BRU1VWV1laW11eX2JmajJkBAAB//8AAAAA'},
           {'category': 'Festival',
            'code': 21785,
            'name': 'Christmas Stripe B',
            'param': 'Qf9/ABgAA0cAAzkAAiT/AAAAAQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyAhIiMMAP8ASElKS0xNTk9QUVJTMmQAAAH//wAAAABvAANhAAMk//8AGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7GAD/ADw9Pj9AQUJDREVGR3h5ent8fX5/gIGCgxj/AABgYWJjZGVmZ2hpamtsbW5vcHFyc3R1dndBZAAAAv//AAAAAFMAA0UAAiQA/wAYGRobHB0eHyAhIiMkJSYnKCkqKywtLi8wMTIzNDU2Nzg5OjsY/38APD0+P0BBQkNERUZHSElKS0xNTk9QUVJTJWQAAAP//wAAAAA='},
           {'category': 'Festival',
            'code': 21786,
            'name': 'Christmas Stripe C',
            'param': 'Qf//AC0AAZ8AA5EAA0L/AAAAAQQHCAsMDRATFBcYGRwfICMkJSgrLC8wMTQ3ODs8PUBDREdISUxPUFNUVVhbXF9gYWRnaGtsbXBzdHd4eXx/gIM3AP8AAgMGCQoODxIVFhobHiEiJicqLS4yMzY5Oj4/QkVGSktOUVJWV1pdXmJjZmlqbm9ydXZ6e36Bggv//wAFER0pNUFNWWVxfTJkAwAB//8AAAAA'},
           {'category': 'Festival',
            'code': 21787,
            'name': 'Christmas Stripe D',
            'param': 'Qf8AAGQAAWcAA1kAAywA/wABBAcKDRATFhkcHyIlKCsuMTQ3Oj1AQ0ZJTE9SVVhbXmFkZ2ptcHN2eXx/gh8AjAAYGhsdHiAhIyQnKSosLS9UVldZWlxdX2BiY2VmaGlrAQCpACYyZAQAAf//AAAAAA=='},
           {'category': 'Festival',
            'code': 21788,
            'name': 'Christmas Gift',
            'param': 'Qf8AAB4AAVwAA04ABA///wAwMTM0PT9KVmBhYmNkbnoGiwD/QkZOT1FSEAD/AEhJS0xUVVdYbG1vcHh5e3wY/38AWltcXV5fZmdoaWprcnN0dXZ3fn+AgYKDMmQEAAH//wAAAAA='},
           {'category': 'Festival',
            'code': 21789,
            'name': 'Christmas Wreath',
            'param': 'Qf8AACUAAVAAA0IAAwz//wADBAUHCBIgOj1RY3InAP8AEBETGhscHR4fISUnLC0uMTI5PkVGSUpSVVZXXF5iZGVmZ2hpcHFzAv8AACZdMmQEAAH//wAAAAA='},
           {'category': 'Festival',
            'code': 21790,
            'name': 'Snow House',
            'param': 'QQAA/xgAAhsAAw0AAQj///8OEzY6SVZYdDJkBwAB//8AAAAAdAADZgAEFP///xESExQmJygpMTIzNDU2PD1CQ0hPJ/8AAB4fKis3Pj9AQUlKS0xNTlRVVldYWVpbYGNkZ2xvcHN4eXp7fH1+fxIA/wAtODk6REVGR1FcXV5oaWprdYEI//8AYWJlZm1ucXIQZAQAAv//AAAAAA=='},
           {'category': 'Festival',
            'code': 21791,
            'name': 'Christmas Tree',
            'param': 'Qf8AADIAAhoAAwwAAQf///8LGiBAUlR/Q2QCAAH//wAAAABjAANVAAM0AP8ABA8RGhscHR4oKTIzNDU2Oj0+P0BBQ0ZLTVJTVldYWVpeYWJjZGVmZ2lrbG1vcXJzdHV2dwj//wAQJ0JMUWpucAz///94eXp7fH1+f4CBgoMyZAQAAv//AAAAAA=='},
           {'category': 'Festival',
            'code': 21792,
            'name': 'Gingerbread Man',
            'param': 'QQD/KigAA0kAAzsAAwb/AAAFBhAREhME////HB0eHyT/fwAoKSorNDU2N0FCSktMTU5PUFFWV1hZWltcXWVmcHFyc3t8f4A0ZAQAAf//AAAAABsAAw0AAgL/fwAhZgL//wAygTJkAgAC//8AAAAAHAADDgACA///AABlggL/fwAebEpkAgAD//8AAAAA'},
           {'category': 'Festival',
            'code': 21793,
            'name': 'Christmas Stocking',
            'param': 'QQD/ADIAATgAAyoAAhn/AAADBBMUHyAqKyw9PklKTU5UVVZdXmlqdHV2CP///wcIMTJCUVJ8Q2QHAAH//wAAAAA='},
           {'category': 'Festival',
            'code': 21794,
            'name': 'Santa Claus',
            'param': 'QQAA/xkAAkgAAzoABA7/AAAREhMUHB0eHygpKitNThL///8hMzQ1Njc4S1BXWFtkZWZncXII/45CQEFCQ0xPWVoByMjIXDBkBAAB//8AAAAAIwADFQADBP8AAAAITm8CAP8AHXUC//8ALj1RZAIAAv//AAAAAA=='},
           {'category': 'Festival',
            'code': 21795,
            'name': 'Grim Graveyard',
            'param': 'Qf8AAAX/AzoAAywAAgT/AAAUFSAhH4sA/z5JSktOT1ZaW2JmZ2prbnJzdnd4eXp7fH1+f4CBgoMxZAQAAf//AAAAACwAAx4AARn///8FERIcHyAnLS4xMjQ1OzxCTk9aXGVocHSBYmQAAQH0AQAAAAAPAAMBAAAyZAABAeQRAAAAAA=='},
           {'category': 'Festival',
            'code': 21796,
            'name': 'Poison',
            'param': 'QQAA/woAAj8AAzEAAwyLAP9gYWJjZGVmZ2hpamsWAP9hbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgQIA/1uCgwBkAAAB//8AAAAALQADHwABGgD/AAIGDRkcIictNDo9QENGS09TX2VqbXN5fH+DUGQBAAL//wAAAAA='},
           {'category': 'Festival',
            'code': 21797,
            'name': 'Lightning Bats',
            'param': 'QQAA/xn/Ay0AAx8AARqLAP8ICRQeHyAmJyoyPD0+SFFSXWNkZ2hpbm9zelxkBQAB//8AAAAAMAADIgABHcjIyAMLDxccIigpKi0zNzg6Pj9DR0lLUFRXXWRpcXZ9YmQAAQIUBQAAAAAPAAMBAAAyZAABATwZAAAAAA=='},
           {'category': 'Festival',
            'code': 21798,
            'name': 'Halloween Witches',
            'param': 'QS0Aiw8AAjcAAykABA2LAP8dHiorTk9ZWltkZWZnBP+RdjY3QkMF/38AVWBhYm0C/7I2Y2hTZAQAAf//AAAAAE8AA0EABAzRtAAAAQIDBAUGBwgJCgsMgngADA0ODxAREhMUFRYXDFBQABgZGhscHR4fICEiIwwyMgAkJSYnKCkqKywtLi8AZAEAAv//AAAAAA=='},
           {'category': 'Festival',
            'code': 21799,
            'name': 'Thanksgiving',
            'param': 'QQAA/xQAAlgAA0oACAH//wBECf9/AExNV1hZWmNkZQP/UwBOT1sB////UwP/AABfa3cI/0ACYmZnaG9xc3QIAIwAbnJ1eXt9gIIIAP8AcHh6fH5/gYMAZAQAAf//AAAAAB0AAw8AAQrIyMgEEic0QEtOV1p8SmQBAAL//wAAAAA='},
           {'category': 'Festival',
            'code': 23040,
            'name': "Mother's Hug",
            'param': 'Qf9oXyMAAcMAA7UADAj/sz8ADA0YGRolJgH/nAABBvq1AAIDBA4PGwr/oEsFBhARHB0nKDM0Hv93NgcIEhMUHh8gKSorLC01Njc4OTpAQUJDREVGTVBRUgr/sDUJCgsVFhchIiMuB/9iViQwMTI8SFQR/2Q/LztHTk9TXF1eX2hpamt2d4MC/zs6PWAl/0ACPj9JSktVVldYWVpbYWJjZGVmZ2xtb3BxcnN0dXh5fH1+f4CBggH/aUpMA/9TAG56ez9kAwAB//8AAAAA'},
           {'category': 'Sleep',
            'code': 8522,
            'name': 'Healing',
            'param': 'QQEBAWQAAn8AA3EABAz/2DEAAQIDBAUGBwgJCgsY/8xBDA0ODxAREhMUFRYXVFVWV1hZWltcXV5fHv/wbBgZGhscHR4fICEiIyQlJicoKSorLC0uL0hJSktMTR7/8JAwMTIzNDU2Nzg5Ojs8PT4/QEFCQ0RFRkdOT1BRUlMyZAQAAf//AAAAAGYAA1gAAzv/XyguMDQ5Ojs8PT9AQURFRkdISUpLTE1OT1BRUlNUVVZXWFlaW1xdXl9gYWJjZGVmZ2hpamtsbW5vcHFycwT7Vgd0dXZ3DP8AAHh5ent8fX5/gIGCg1FYAwAB//8AAAAA'},
           {'category': 'Sleep', 'code': 47, 'name': 'Starry Sky', 'param': ''},
           {'category': 'Sleep',
            'code': 8523,
            'name': 'Accompany',
            'param': 'QQOrNjQAA5MAA4UAAxIAvtsAAQIDBAUGBwgJCgsNDxETFRdUHP9aDA4QEhQWGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PT9BQ0VHSEpMTlBSVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG5wcnR2Eo3/G21vcXN1d3h5ent8fX5/gIGCg1VkAwAC//8AAAAAPwADMQADCf//ACQlJicoKSorLBL/fwBISUpLTE1OT1BgYWJjZGVmZ2gJ/74LeHl6e3x9fn+APEYEAAH//wAAAAA/AAMxAAMJ//8AGxwdHh8gISIjEv9/ADM0NTY3ODk6O1dYWVpbXF1eXwn/vgt7fH1+f4CBgoM8RgMAAf//AAAAAA=='},
           {'category': 'Sleep',
            'code': 8524,
            'name': 'Dreamland',
            'param': 'QQEBAWQAAbMAA6UACCQAAP8AAQIDBAUGBwgJCgsMDQ4PEBESExQVFhd4eXp7fH1+f4CBgoMMiwD/GBkaGxwdHh8gISIjDP8AbiQlJicoKSorLC0uLwz/AAAwMTIzNDU2Nzg5OjsY/38APD0+P0BBQkNERUZHSElKS0xNTk9QUVJTDOmFh1RVVldYWVpbXF1eXwwA//9gYWJjZGVmZ2hpamsMBlHBbG1ub3BxcnN0dXZ3XWQBAAH//wAAAAA='},
           {'category': 'Sleep',
            'code': 8525,
            'name': 'Night',
            'param': 'QWwApRcAAm8AA2EAAwwAAP8AAQIDBAUGBwgJCgseSxm3DA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJScpKy0vKmwApSQmKCosLjAxMjM0NTY3ODk6Ozw9Pj9AQUJDREVGR0hJSktMTU5PUFFSUzIGAwAC//8AAAAAPwADMQADEuZhFWBiZGZoamxtbm9wcXJzdHV2dwa0FBRhY2VnaWsM/8Y0eHl6e3x9fn+AgYKDSzwDAAH//wAAAAA='},
           {'category': 'Sleep',
            'code': 8526,
            'name': 'Mysterious',
            'param': 'QQEBATIAAVUAA0cAAiqLAP8LDBYXGBkhIiMkJSYsLS4xMjM3ODk/QEFCQ0pLT1BVVlxdYGFpamx2d4MUAAD/LzA6Ozw9PkRFRkdISVFSU1ReX2tWZAQAAv//AAAAAA=='},
           {'category': 'Sleep',
            'code': 8527,
            'name': 'Soothing',
            'param': 'QQEBAVYAA3UAA2cAAzAA/wAAAQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGhweICIlJykrLS8wMjQ2ODo9P0FDRUcpxP8AGRsdHyEjJCYoKiwuMTM1Nzk8PkBCREZISUpLTE1OT1BRUlNUVlhaXF4B1/8AO05fBAAB//8AAAAAdQADZwADJP/wkCUnKSstLzAxMjM0NTY3ODk6Ozw9Pj9AQUJDREVGR0hKTE5QUhL/8GxJS01PUVNUVVZXWFlaW1xdXl8k/9gxYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDC2QDAAL//wAAAABLAAM9AAMYcv9yDQ8RExUXGBkaGxwdHh8gISIjPD5AQkRGDAD/ACQlJicoKSorLC0uLwz/8JAwMTIzNDU2Nzg5Ojs8ZAEAAf//AAAAAA=='},
           {'category': 'Starry Sky',
            'code': 8528,
            'name': 'Earth',
            'param': 'QQEBAWQAA2gAA1oAAyMWgCUYGRwdHiEiIyQlJiwtLi8yMzQ1Nzg5Ojs8P0BGR0xNTk9TWR4AlhRISUpLUFFSVFVWV1haW1xdXl9gYWJjZGVmZ2hpamsMAAD/bG1ub3BxcnN0dXZ3UmQEAAH//wAAAACLAAN9AAQM//8AAAECAwQFBgcICQoLFP//ZQwNDg8QERITFBUWFxkdICIpKjA6PP/wkBgaGxweHyEjJTEyMzw9Pj9AQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVpbXF1eX2BhYmNkZWZnaGlqaxD/8GwkJicoKywtLi80NTY3ODk7MWQDAAP//wAAAAB7AANtAAMhFoAlGBkcHR4hIiMkJSYtLi8yMzQ1ODk6Ozw/QEZHTE1OT1NZIQAA/xobHyAnKCkqKywwMTY3PT5BQkNERWxtbm9wcXJzdHV2dx4AlhRISUpLUFFSVFVWV1haW1xdXl9gYWJjZGVmZ2hpamtSUAMAAv//AAAAAA=='},
           {'category': 'Starry Sky',
            'code': 8529,
            'name': 'Mars',
            'param': 'QQEBAWQAA18AA1EAAiT7Vgc8PT4/QEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaW1xdXl8k/wAAYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDUFABAAL//wAAAAC3AAOpAAkU+1YHAAIkMDQ1NjxISVVaYGhpbG5ydXYp/6sFAQoLDA0ODxYXGB4iIyUnKSorLC4vPT4/QEJFRkdSU1RWWFldXl9mamsF/74LAwRXb3AM8XMABQYQEhkcHSYoQURzFv+VBQcICRMUFR8gIS03ODlDTU5PW2FiZXEF/wAAERobUG0M/38AMTIzOjtKS0xjZGd3A8xYA1FcdAz/hgB4eXp7fH1+f4CBgoNOZAMAA///AAAAACsAAx0AARj/vgtISUpLTE1OT1BRUlNUVVZXWFlaW1xdXl9aZAIAAf//AAAAAA=='},
           {'category': 'Starry Sky',
            'code': 8530,
            'name': 'Venus',
            'param': 'QQEBAWQAA1MAA0UAAh7/fwAAAQIDBAUGBwgJCgtKS0xPUFFsbW5vcHFyc3R1dnce/xYAGBkaGxwdHh8gISIjJCUmJygpKissLS4vSElNTlJTUkYDAAH//wAAAABYAANKAAFF/38AAAECAwQFBgcICQoLGBkaGxwdHh8gISIjJygpKissLS4vSElKS0xNTk9QVFVWV1hZWltccnN0dXZ3eHl6e3x9fn+AgYKDWmQDAAL//wAAAACjAAOVAAQM/38AAAECAwQFBgcICQoLJ65AKAwNDg8QERITFBUWFzw9Pj9AQUJDREVGR0hJSktMTU5PUFFSU1dYWSb/2DEYGRobHB0eHyAhIiMmJygpKissLS4vXHV2d3h5ent8fX5/gIGCgyv/zEEkJTAxMjM0NTY3ODk6O1RVVlpbXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0WmQEAAL//wAAAAA='},
           {'category': 'Starry Sky',
            'code': 8531,
            'name': 'Uranus',
            'param': 'QQEBAWQAAnsAA20AAz8AAP8MDQ4PEBESExQVFhc8PT4/QEFCQ0RFRkdISUpLTE1OT1BRUlNXXF1ebG1ub3BxcnN0dXZ3eXp7fH1+f4CBgoMgAP//MDEyMzQ1Njc4OTo7VFVWWFlaW19gYWJjZGVmZ2hpamsBBlHBeDJkBAAB//8AAAAAcQADYwAGGAAA/wABAgMEBQYHCAkKCwwNDg8QERITFBUWFww+z+QYGRobHB0eHyAhIiMM////JCUmJygpKissLS4vCoM47Dw9PkFCQ0RFRkcE//CQWltcXQwhLb5sbW5vcHFyc3R1dndTWwMAAv//AAAAAA=='},
           {'category': 'Starry Sky',
            'code': 8532,
            'name': 'Jupiter',
            'param': 'QQEBAUMAA4AAA3IABQz/fwAAAQIDBAUGBwgJCgsff0IAJCUmJyorLC0uL1RVVldYWVpbXF1eX21ub3BzdHV2dxr/zEEoKTAxMjM0NTY3ODk6O0hJSktMTU5PUFFSUxf/hgBgYWJjZGVmZ2hpamt4eXp7fH1+f4CBggH/nzyDVloDAAH//wAAAAB/AANxAAQMrkAoAAECAwQFBgcICQoLJP+fPAwNDg8QERITFBUWFyQlJicoKSorLC0uLzAxMjM0NTY3ODk6OxgA//8YGRobHB0eHyAhIiM8PT4/QEFCQ0RFRkcY+sGGYGFiY2RlZmdoaWpreHl6e3x9fn+AgYKDT1oDAAL//wAAAAAbAAMNAAEI/wAAQkNERU5PUFFaVAMAAf//AAAAAA=='},
           {'category': 'Starry Sky',
            'code': 8533,
            'name': 'Milky Way',
            'param': 'QQAA/xUAAj0AAy8ACAH//wAiAQD//ykBxQA/LAL/fwAxSQP/8Gw8PT4EAAD/Tk9aWwEA/wBjATH/k3hVXwcAAf//AAAAAFEAA0MAAxH//wAKCxUWICssNjdBQkxNV2JteBj/4BYXISIjLS44OUNETk9YWVpjZGVub3B5ensNby29U11eX2hpanN0dX5/gChkBwAB//8AAAAA'},
           {'category': 'Life',
            'code': 20901,
            'name': 'Graffiti 4',
            'param': 'AFI6ZAwAAP8A//+lvv4XWv4='},
           {'category': 'Life',
            'code': 8505,
            'name': 'Gleam',
            'param': 'AFMAIxX/AAD/fwD//wAA/wAAAP8A//+LAP8='},
           {'category': 'Other',
            'code': 20902,
            'name': 'Judy',
            'param': 'QSYA/yMAA0wAAz4AAx60tMgECBETHR8pKzU3QEFCQ0RLTE1OT1BRV1hcXWNpcHQI+wBFEBQcICgsNDgL////WVpbZGVmZ2hxcnM0ZAQAAf//AAAAABcAAwkAAQT7AEUWHElpMmQAAAL//wAAAAAXAAMJAAEE+wBFAUJudEVkAAAD//8AAAAA'},
           {'category': 'Other',
            'code': 20903,
            'name': 'Nick',
            'param': 'Qf87gx4AA1oAA0wABAb/AAAOFhobISIG/0ACHCYnKTM0B/89ASAoKywtLjko/38AKjU2Nzg/QEFCQ0RFSktMTU5PUFFSVldYWVpbXF1eY2RlZmdoaXFyczRkBAAB//8AAAAAGQADCwABBv//AA4XNV1hgzJkAAAC//8AAAAAGQADCwABBv//ABcZH01udkRkAAAD//8AAAAA'},
           {'category': 'Other',
            'code': 20904,
            'name': 'ZDP Duo',
            'param': 'QQEBAWQAAjYAAygAASMAAP8BAgcIDA0SExgdHigpMzQ7Pj9GR0lKUVJUVVxdYGdocnN9flFkBwAB//8AAAAANgADKAABI/9TAAQFDxAXGhsiIyUmLS4wMTg5PENETk9ZWmRla29wdnd6e4GCU2QGAAL//wAAAAA='},
           {'category': 'Other',
            'code': 20905,
            'name': 'ZDP Trio',
            'param': 'QQEBAWQAAyMAAxUAARAAAP8HCBITHR4oKTM0Pj9JSlRVYmQGAAH//wAAAAAwAAMiAAMKiwD/BRARGxwmJzEyPQb/AGFERU9QWlsF/2hJZWZwcXxeZAYAAv//AAAAALMAA6UACBj/aUoAAQIDBAUGBwgJCgsMDQ4PEBESExQVFhcM7TSlGBkaGxwdHh8gISIjDGwApSQlJicoKSorLC0uLxgAAP8wMTIzNDU2Nzg5Ojs8PT4/QEFCQ0RFRkcMQE7KSElKS0xNTk9QUVJTDJk6w1RVVldYWVpbXF1eXxj/O4NgYWJjZGVmZ2hpamtsbW5vcHFyc3R1dncM/0ACeHl6e3x9fn+AgYKDPmQHAAP//wAAAAA='}]}
